apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-frontend
  namespace: healthcare-app
  labels:
    app: healthcare-frontend
    tier: frontend
    component: web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-frontend
  template:
    metadata:
      labels:
        app: healthcare-frontend
        tier: frontend
        component: web-server
    spec:
      containers:
      - name: healthcare-frontend
        image: asia-south1-docker.pkg.dev/hc-3-monitoring/healthcare-repo/healthcare-frontend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: healthcare-config
              key: NODE_ENV
        - name: REACT_APP_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: healthcare-config
              key: REACT_APP_API_BASE_URL
        - name: BACKEND_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: healthcare-config
              key: BACKEND_SERVICE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-frontend-service
  namespace: healthcare-app
  labels:
    app: healthcare-frontend
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: healthcare-frontend

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-frontend-nodeport
  namespace: healthcare-app
  labels:
    app: healthcare-frontend
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: healthcare-frontend