apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-mongodb
  namespace: healthcare-app
  labels:
    app: healthcare-mongodb
    component: database
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-mongodb
  template:
    metadata:
      labels:
        app: healthcare-mongodb
        component: database
        tier: database
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
          protocol: TCP
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: healthcare-secrets
              key: MONGO_PASSWORD
        - name: MONGO_INITDB_DATABASE
          value: "healthcare"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /data/configdb
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 60    # Increased for MongoDB initialization
          periodSeconds: 30          # Check every 30 seconds
          timeoutSeconds: 10         # Allow 10 seconds for response
          failureThreshold: 3        # Fail after 3 consecutive failures
          successThreshold: 1
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30    # Wait 30 seconds before first check
          periodSeconds: 10          # Check every 10 seconds
          timeoutSeconds: 10         # Allow 10 seconds for response
          failureThreshold: 3        # Fail after 3 consecutive failures
          successThreshold: 1
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-data-pvc
      - name: mongodb-config
        persistentVolumeClaim:
          claimName: mongodb-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-mongodb-service
  namespace: healthcare-app
  labels:
    app: healthcare-mongodb
    component: database
    tier: database
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: healthcare-mongodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
  namespace: healthcare-app
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-config-pvc
  namespace: healthcare-app
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi