apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthcare-ingress
  namespace: healthcare-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
  - host: healthcare.local  # You can change this to your domain
    http:
      paths:
      # Frontend routes
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: healthcare-frontend-service
            port:
              number: 3000
      # Backend API routes
      - path: /(api/.*)
        pathType: Prefix
        backend:
          service:
            name: healthcare-backend-service
            port:
              number: 5002
      # Backend health check
      - path: /(health)
        pathType: Prefix
        backend:
          service:
            name: healthcare-backend-service
            port:
              number: 5002
      # Backend metrics
      - path: /(metrics)
        pathType: Prefix
        backend:
          service:
            name: healthcare-backend-service
            port:
              number: 5002
---
# Alternative ingress for LoadBalancer IP access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthcare-ingress-ip
  namespace: healthcare-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
  - http:
      paths:
      # Frontend routes (catch-all, should be last)
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: healthcare-frontend-service
            port:
              number: 3000
      # Backend API routes
      - path: /(api/.*)
        pathType: Prefix
        backend:
          service:
            name: healthcare-backend-service
            port:
              number: 5002
      # Backend health check
      - path: /(health)
        pathType: Prefix
        backend:
          service:
            name: healthcare-backend-service
            port:
              number: 5002
      # Backend metrics
      - path: /(metrics)
        pathType: Prefix
        backend:
          service:
            name: healthcare-backend-service
            port:
              number: 5002